import { JobApplication } from "@/@types/jobTypes";

export const sampleJobs: JobApplication[] = [
  {
    id: "job-1",
    company: "Google",
    roleTitle: "Software Engineer",
    jobDescription:
      "Building next-generation cloud infrastructure and distributed systems.",
    jobType: "Full-time",
    salary: "$150,000 - $200,000",
    workSetup: "Hybrid",
    workSchedule: "9am - 5pm",
    location: "Mountain View, CA",
    jobLink: "https://careers.google.com",
    applicationMethod: "Company Website",
    applicationDate: "2026-02-15",
    status: "Interview",
    priority: "High",
    cvVersion: "CV_v3.2",
    coverLetterSent: true,
    contact: "recruiter@google.com",
    interviewStage: "Technical Interview",
    interviewDate: "2026-02-28",
    interviewTime: "14:00",
    interviewerName: "Sarah Johnson",
    offer: false,
    notes: "Very excited about this opportunity. Team seems great!",
  },
  {
    id: "job-2",
    company: "Meta",
    roleTitle: "Frontend Engineer",
    jobDescription: "Work on React and building immersive social experiences.",
    jobType: "Full-time",
    salary: "$140,000 - $180,000",
    workSetup: "Remote",
    location: "Remote",
    jobLink: "https://metacareers.com",
    applicationMethod: "LinkedIn",
    applicationDate: "2026-02-10",
    status: "Under Review",
    priority: "High",
    cvVersion: "CV_v3.2",
    coverLetterSent: true,
    contact: "hiring@meta.com",
    interviewStage: "None",
    offer: false,
    notes: "Referral from John. Strong team culture.",
  },
  {
    id: "job-3",
    company: "Amazon",
    roleTitle: "Software Development Engineer",
    jobDescription:
      "Building scalable e-commerce solutions for millions of customers.",
    jobType: "Full-time",
    salary: "$130,000 - $170,000",
    workSetup: "On-site",
    location: "Seattle, WA",
    jobLink: "https://amazon.jobs",
    applicationMethod: "Referral",
    applicationDate: "2026-02-08",
    status: "Offer",
    priority: "High",
    cvVersion: "CV_v3.1",
    coverLetterSent: true,
    contact: "jane.smith@amazon.com",
    interviewStage: "Offer Stage",
    interviewDate: "2026-02-20",
    interviewTime: "10:00",
    interviewerName: "Michael Chen",
    offer: true,
    notes: "Great offer! Need to decide by end of week.",
  },
  {
    id: "job-4",
    company: "Stripe",
    roleTitle: "Full Stack Engineer",
    jobDescription: "Building payment infrastructure for the internet.",
    jobType: "Full-time",
    salary: "$160,000 - $190,000",
    workSetup: "Remote",
    location: "San Francisco, CA",
    jobLink: "https://stripe.com/jobs",
    applicationMethod: "Company Website",
    applicationDate: "2026-02-05",
    status: "Applied",
    priority: "Medium",
    cvVersion: "CV_v3.0",
    coverLetterSent: false,
    interviewStage: "None",
    offer: false,
    notes: "Applied through company website. Waiting for response.",
  },
  {
    id: "job-5",
    company: "Netflix",
    roleTitle: "UI Engineer",
    jobDescription: "Create stunning user interfaces for streaming platform.",
    jobType: "Full-time",
    salary: "$145,000 - $185,000",
    workSetup: "Hybrid",
    location: "Los Gatos, CA",
    jobLink: "https://jobs.netflix.com",
    applicationMethod: "LinkedIn",
    applicationDate: "2026-01-28",
    status: "Rejected",
    priority: "Medium",
    cvVersion: "CV_v3.0",
    coverLetterSent: true,
    contact: "talent@netflix.com",
    interviewStage: "HR Screening",
    interviewDate: "2026-02-05",
    interviewTime: "11:00",
    interviewerName: "Lisa Brown",
    offer: false,
    notes: "Not a good fit for the role. Focus on backend roles instead.",
  },
  {
    id: "job-6",
    company: "Airbnb",
    roleTitle: "Software Engineer",
    jobDescription: "Building tools to help people belong anywhere.",
    jobType: "Full-time",
    salary: "$135,000 - $175,000",
    workSetup: "Hybrid",
    location: "San Francisco, CA",
    applicationMethod: "Referral",
    applicationDate: "2026-02-18",
    status: "Interview",
    priority: "High",
    cvVersion: "CV_v3.2",
    coverLetterSent: true,
    contact: "careers@airbnb.com",
    interviewStage: "HR Screening",
    interviewDate: "2026-02-25",
    interviewTime: "15:00",
    interviewerName: "David Lee",
    offer: false,
    notes: "HR screening went well. Technical round next week.",
  },
  {
    id: "job-7",
    company: "Spotify",
    roleTitle: "Backend Engineer",
    jobDescription: "Building music streaming infrastructure at scale.",
    jobType: "Full-time",
    salary: "$125,000 - $165,000",
    workSetup: "Remote",
    location: "Remote",
    applicationMethod: "Company Website",
    applicationDate: "2026-02-12",
    status: "Applied",
    priority: "Low",
    cvVersion: "CV_v3.1",
    coverLetterSent: true,
    interviewStage: "None",
    offer: false,
  },
  {
    id: "job-8",
    company: "Shopify",
    roleTitle: "Full Stack Developer",
    jobDescription: "Empowering entrepreneurs with commerce tools.",
    jobType: "Full-time",
    salary: "$120,000 - $160,000",
    workSetup: "Remote",
    location: "Toronto, Canada",
    applicationMethod: "LinkedIn",
    applicationDate: "2026-02-01",
    status: "Withdrawn",
    priority: "Low",
    cvVersion: "CV_v3.0",
    coverLetterSent: false,
    interviewStage: "None",
    offer: false,
    notes: "Decided to focus on US-based opportunities.",
  },
  {
    id: "job-9",
    company: "Shopify",
    roleTitle: "Full Stack Developer",
    jobDescription: "Empowering entrepreneurs with commerce tools.",
    jobType: "Full-time",
    salary: "$120,000 - $160,000",
    workSetup: "Remote",
    location: "Toronto, Canada",
    applicationMethod: "LinkedIn",
    applicationDate: "2026-02-01",
    status: "Withdrawn",
    priority: "Low",
    cvVersion: "CV_v3.0",
    coverLetterSent: false,
    interviewStage: "None",
    offer: false,
    notes: "Decided to focus on US-based opportunities.",
  },
];
